version: "3"

# Access site at http://${NAME}.develop
# Point search_api_solr to http://${NAME}-solr:8983/solr/#/drupal

services:

  php:
    image: wodby/drupal-php:${PHP_TAG}
    container_name: ${NAME}-php
    environment:
      PHP_DOCROOT: ${DOCROOT} # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog.develop:1025
      PHP_FPM_MAX_CHILDREN: 16
      PHP_MEMORY_LIMIT: 1024M
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1              # Renamed from PHP_XDEBUG_ENABLED in latest version.
      PHP_XDEBUG_REMOTE_AUTOSTART: 1            # Renamed from PHP_XDEBUG_AUTOSTART in latest version.
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal
      PHP_XDEBUG_MAX_NESTING_LEVEL: 2048
      PHP_IDE_CONFIG: serverName=${NAME}.develop
    volumes:
      - ./:/var/www/html:delegated
    external_links:
      - mysql
    networks:
      - default
      - commonapps_default

  nginx:
    image: wodby/drupal-nginx:8-1.15
    container_name: ${NAME}-nginx
    environment:
      VIRTUAL_HOST: ${NAME}.develop # This tell global proxy about this container.
      NGINX_BACKEND_HOST: ${NAME}-php
      NGINX_BACKEND_PORT: 9000
      NGINX_SERVER_NAME: ${NAME}.develop
      NGINX_SERVER_ROOT: /var/www/html/${DOCROOT}
      DRUPAL_VERSION: ${DRUPAL_VERSION}  # Allowed: 7, 8.
    volumes:
      - ./:/var/www/html:delegated
    labels:
      - 'traefik.backend=${NAME}-nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${NAME}.develop'
    depends_on:
      - php
    networks:
      - default
      - commonapps_default

  # Solr: configure search_api_solr to connect to http://${NAME}-solr:8983/solr/#/drupal
  solr:
    image: solr:6.6.4
    container_name: ${NAME}-solr # visit me at http://${NAME}-solr:8983/solr !
    volumes:
      - ./sites/all/modules/contrib/search_api_solr/solr-conf/6.x:/myconfig/conf
      - ./.solr-data:/opt/solr/server/solr/mycores
    environment:
      VIRTUAL_HOST: ${NAME}-solr.develop
      VIRTUAL_PORT: 8983
      SOLR_UID: 0
      SOLR_USER: root # Crazyness, I know. Found no other way because docker initiates .solr-data as root.      SOLR_USER: root # Crazyness, I know. Found no other way because docker initiates .solr-data as root.
    labels:
      - 'traefik.backend=${NAME}-solr'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:${NAME}-solr.develop'
    networks:
      - default
      - commonapps_default
    entrypoint:
      - solr-precreate
      - drupal
      - /myconfig

#  selenium-hub:
#    image: selenium/hub:3.12.0-cobalt
#    container_name: ${NAME}-selenium-hub
#    ports:
#      - "4444:4444"
#    labels:
#      - 'traefik.backend=${NAME}-selenium-hub'
#      - 'traefik.port=4444'
#      - 'traefik.frontend.rule=Host:${NAME}-selenium-hub.develop'
#    networks:
#      - default
#      - commonapps_default

#  # Chrome: To watch the tests run visit ${NAME}-chrome:5900 in a VNC viewer.
#  chrome:
#    image: selenium/node-chrome-debug:3.12.0-cobalt
#    container_name: ${NAME}-chrome
#    ports:
#      - "5900:5900"
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=${NAME}-selenium-hub
#      - HUB_PORT=4444
#    labels:
#      - 'traefik.backend=${NAME}-chrome'
#      - 'traefik.port=5900'
#      - 'traefik.frontend.rule=Host:${NAME}-chrome.develop'
#    networks:
#      - default
#      - commonapps_default

#  phantomjs:
#    image: wernight/phantomjs:2
#    volumes_from:
#      - php
#    links:
#      - nginx:${NAME}.develop
#    networks:
#      - default
#      - commonapps_default
#    entrypoint: phantomjs
#    command: "--ssl-protocol=any --ignore-ssl-errors=true /var/www/html/vendor/jcalderonzumba/gastonjs/src/Client/main.js 8510 1024 768"

#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - "8002:8025"

#  redis:
#    image: redis:3.2-alpine

#  memcached:
#    image: memcached:1.4-alpine

#  memcached-admin:
#    image: phynias/phpmemcachedadmin
#    ports:
#      - "8006:80"

#  clamd:
#    image: dinkel/clamavd
#    container_name: ${NAME}-clamav

#  pma:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mariadb
#      PMA_USER: drupal
#      PMA_PASSWORD: drupal
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#     ports:
#     - "8001:80"

networks:
  commonapps_default:
    external: true
