version: "3"

# Access site at http://${NAME}.develop
# Point search_api_solr to http://${NAME}-solr:8983/solr/#/drupal

services:

  php:
    image: wodby/drupal-php:${PHP_TAG}
    container_name: ${NAME}-php
    environment:
      PHP_DOCROOT: ${DOCROOT} # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog.develop:1025
      PHP_FPM_MAX_CHILDREN: 16
      PHP_MEMORY_LIMIT: 512M
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal
      PHP_XDEBUG_MAX_NESTING_LEVEL: 2048
      PHP_XDEBUG_PROFILER_ENABLE: 0
      PHP_XDEBUG_PROFILER_ENABLE_TRIGGER: 1     # Use ?XDEBUG_PROFILE=1 to enable
      PHP_IDE_CONFIG: serverName=${NAME}.develop
    volumes:
      - ./:/var/www/html:delegated
      - ./files:/mnt/files
      - docker-sync:/var/www/html:nocopy
    external_links:
      - mysql
    networks:
      - default
      - commonapps_default

  nginx:
    image: wodby/drupal-nginx:8-1.15
    container_name: ${NAME}-nginx
    environment:
      VIRTUAL_HOST: ${NAME}.develop
      NGINX_BACKEND_HOST: ${NAME}-php
      NGINX_BACKEND_PORT: 9000
      NGINX_SERVER_NAME: ${NAME}.develop
      NGINX_SERVER_ROOT: /var/www/html/${DOCROOT}
      NGINX_ERROR_LOG_LEVEL: debug
    volumes:
      - ./:/var/www/html:delegated
      - docker-sync:/var/www/html:nocopy
    labels:
      - 'traefik.backend=${NAME}-nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${NAME}.develop'
    depends_on:
      - php
    networks:
      - default
      - commonapps_default

  # Solr: configure search_api_solr to connect to http://${NAME}-solr:8983/solr/#/drupal
  solr:
    image: solr:6.6.4
    container_name: ${NAME}-solr # visit me at http://${NAME}-solr:8983/solr !
    volumes:
      - ./sites/all/modules/contrib/search_api_solr/solr-conf/6.x:/myconfig/conf
      - ./.solr-data:/opt/solr/server/solr/mycores
    environment:
      VIRTUAL_HOST: ${NAME}-solr.develop
      VIRTUAL_PORT: 8983
      SOLR_UID: 0
      SOLR_USER: root # Crazyness, I know. Found no other way because docker initiates .solr-data as root.      SOLR_USER: root # Crazyness, I know. Found no other way because docker initiates .solr-data as root.
    labels:
      - 'traefik.backend=${NAME}-solr'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:${NAME}-solr.develop'
    networks:
      - default
      - commonapps_default
    entrypoint:
      - solr-precreate
      - drupal
      - /myconfig

#  selenium-hub:
#    image: selenium/hub:3.12.0-cobalt
#    container_name: ${NAME}-selenium-hub
#    ports:
#      - "4444:4444"
#    labels:
#      - 'traefik.backend=${NAME}-selenium-hub'
#      - 'traefik.port=4444'
#      - 'traefik.frontend.rule=Host:${NAME}-selenium-hub.develop'
#    networks:
#      - default
#      - commonapps_default

#  # Chrome: To watch the tests run visit ${NAME}-chrome:5900 in a VNC viewer.
#  chrome:
#    image: selenium/node-chrome-debug:3.12.0-cobalt
#    container_name: ${NAME}-chrome
#    ports:
#      - "5900:5900"
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=${NAME}-selenium-hub
#      - HUB_PORT=4444
#    labels:
#      - 'traefik.backend=${NAME}-chrome'
#      - 'traefik.port=5900'
#      - 'traefik.frontend.rule=Host:${NAME}-chrome.develop'
#    networks:
#      - default
#      - commonapps_default

#  phantomjs:
#    image: wernight/phantomjs:2
#    volumes_from:
#      - php
#    links:
#      - nginx:${NAME}.develop
#    networks:
#      - default
#      - commonapps_default
#    entrypoint: phantomjs
#    command: "--ssl-protocol=any --ignore-ssl-errors=true /var/www/html/vendor/jcalderonzumba/gastonjs/src/Client/main.js 8510 1024 768"

#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - "8002:8025"

#  memcached:
#    image: wodby/memcached:1.5-2.1.1
#    container_name: ${NAME}-memcached
#    ports:
#      - "11211:11211"
#    labels:
#      - 'traefik.backend=${NAME}-memcached'
#      - 'traefik.port=11211'
#      - 'traefik.frontend.rule=Host:${NAME}-memcached.develop'
#    command: ['-m', '512m']

#  memcached-admin:
#    image: jacksoncage/phpmemcachedadmin
#    container_name: ${NAME}-memcached-admin
#    environment:
#      MEMCACHED_SERVER: ${NAME}-memcached
#    volumes:
#      - ./docker-memcache.php:/phpmemcachedadmin/Config/Memcache.php
#    ports:
#      - "8600:80"
#    labels:
#      - 'traefik.backend=${NAME}-memcached'
#      - 'traefik.port=8600'
#      - 'traefik.frontend.rule=Host:${NAME}-memcached-admin.develop'

#  redis:
#    image: redis:3.2-alpine

#  clamd:
#    image: dinkel/clamavd
#    container_name: ${NAME}-clamav

#  webgrind:
#    image: wodby/webgrind:$WEBGRIND_TAG
#    container_name: ${NAME}-webgrind
#    environment:
#      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug/profiler
#    labels:
#      - 'traefik.backend=webgrind'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:${NAME}-webgrind.develop'
#    volumes:
#      - files:/mnt/files

networks:
  commonapps_default:
    external: true

volumes:
  docker-sync:
    external:
      name: "${NAME}-sync"
